//
// Created by Erik Dvorcak on 2019-05-04.
//

#ifndef COMMUNICATIONSERVER_CONSTANTS_H
#define COMMUNICATIONSERVER_CONSTANTS_H

#define STATUS_ONLINE 1
#define STATUS_ON_REPAIR 2
#define STATUS_OFFLNE 3
#define STATUS_COMMUNICATION_ERROR 4
#define STATUS_STAND_BY 5

#endif //COMMUNICATIONSERVER_CONSTANTS_H